on:
 push:
   branches:
   - '*'
   paths:
   - '*'
   - '!*.md'
   - '!**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo $payload
      env:
        payload: ${{ toJson(github) }}
