name: CI
on:
  push

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            conxt sha = context.sha;
            
            const commit_details = await github.git.getCommit({owner, repo, sha});
            console.log(commit_details.author.date);
    
   
