name: CI
on:
  push

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        id: author-date
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |             
            const core = require('@actions/core');
            const commit_details = await github.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});
            return commit_details.data.author.date
      - run: env
        env:
          COMMITTED_AT: ${{ steps.author-date.outputs.result }}
   
