name: CI
on:
  push

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context.repo.owner);
            console.log(context.repo.repo);
   
