name: CI
on:
  push

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commit_details = await github.git.getCommit({context.repo.owner, context.repo.repo, context.sha});
            console.log(commit_details.author.date);
    
   
